train:
  max_epochs: 10
  accelerator: "cpu"  # Или "gpu", если используете GPU
  devices: 1
  checkpoint:
    monitor: "val_loss"
    dirpath: "checkpoints"
    filename: "model-{epoch:02d}-{val_loss:.2f}"
    save_top_k: 1
    mode: "min"
